version: '3'

services:

    collector:
        build: .
        env_file:
            - .env
        environment:
            - AVMON_ROLE=collector
            - AVMON_WAIT_FOR_DBS=1
            - AVMON_KAFKA=kafka
        volumes:
          - ${PWD}/avmon.cfg.toml:/app/avmon.cfg.toml
        depends_on:
            - backend
            - kafka

    backend:
        build: .
        env_file:
            - .env
        environment:
            - AVMON_ROLE=backend
            - AVMON_WAIT_FOR_DBS=1
            - AVMON_KAFKA=kafka
            - POSTGRES_HOST=postgres
        depends_on:
            - postgres
            - kafka

    frontend:
        build: .
        env_file:
            - .env
        environment:
            - AVMON_ROLE=frontend
            - AVMON_WAIT_FOR_DBS=1
            - POSTGRES_HOST=postgres
        depends_on:
            - postgres
        ports:
            - "8080:8080"


    postgres:
        image: "postgres"
        environment:
            - POSTGRES_USER=user
            - POSTGRES_DB=avmon
        env_file:
            - .env
        ports:
            - "5432:5432"


    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        depends_on:
            - zookeeper
