# Default poll interval for endpoint
interval = 60

[[endpoint]]
url = "https://aiven.io/"
description = "Aiven"

[[endpoint]]
url = "https://google.com/"
description = "Google"

[[endpoint]]
interval = 45 # Overwrite interval
url = "https://worldtimeapi.org/api/ip.txt"
description = "Current time for client IP"
# Match time with even number of minutes
regex = "datetime: \\d+-\\d+-\\d+T\\d+:\\d+"

[[endpoint]]
interval = 2
url = "http://httpbin.org/status/200,500"
description = "Randomly failing endpoint"

[[endpoint]]
url = "http://httpbin.org/status/400"
description = "Always failing endpoint"

[[endpoint]]
timeout = 1.5
url = "http://httpbin.org/delay/10"
description = "Endpoint with a 10 second delay"
